### ISSUE TITLE
To Francesco or Giuseppe? - keyword search results seems very few

### ISSUE THREAD

**Issue by sunbrn** [armando2603/virus-project#15]
It is quite strange that I always get about 6/9 papers, regardless of which search I make. 

For example, I got 6, when I typed "K417N" effects

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/11488353/162972886-27e8d19b-98bb-4185-9c9d-0f542d561826.png">

However, if I look for the same keywords on CORD-19 I get several thousand... 
https://www.semanticscholar.org/search?q=K417N%20effects&sort=relevance

Are we doing the correct thing? 
I remember you mentioned needing to remove some hardcoded limit... maybe it is still there, getting less than 10 results?

**Comment by FrInve** [comment]
Hi,
I've reindexed the dataset removing all the limits and removed the bound from the search object in db13492c295cb7d9f336672335c1d62d7cdda602
Now the system can recall 258 papers with 'K417N', that is the same quantity I can recall by hand with the dataset loaded on pandas.
The interface may show fewer results at the beginning, but they load while scrolling down.
