### ISSUE TITLE
Session name not working

### ISSUE THREAD

**Issue by sunbrn** [armando2603/virus-project#16]
It seems the session naming mechanism is not working.

When I get to the "annotation page" it says No Session Name
<img width="819" alt="image" src="https://user-images.githubusercontent.com/11488353/162973429-bf7dc538-c419-4db7-b094-d93c7d35cff6.png">

and when I download the the session it does not ask me to provide a name, just downloads a session.json

**Comment by cuya26** [comment]
The session form appears now when the user add an annotation and when the user save a session
