### ISSUE TITLE
Nice to have: adding examples

### ISSUE THREAD

**Issue by RubaAlkhalaf** [armando2603/virus-project#7]
It would be nice if you write an example of the optimum way to write a mutation/group/variant to explain the used syntax to the user.
For example:
Substitution: SPIKE_E484K  
Deletion: SPIKE_H69-
Insertion: SPIKE_100A (no need for a reference) 
With the note about considering each amino acid change as single entity even if the changes were merged together in case of successive changes.
For example:
SPIKE_IHV68del is considered as a group of three changes, that are: SPIKE_I68- , SPIKE_H69- , SPIKE_V70-

**Comment by armando2603** [comment]
I will add the instructions for the user in the interface. Can you please provide the full text that you want the user see in the interface?
